# Generated by Django 4.1.3 on 2022-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=123)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
